In [3]:
import pandas as pd

df = pd.read_csv("datasev.csv") 

df

,id,Nombre,Apodo,Localidad,Fundación,División,Estadio,Capacidad,Figura,Director Técnico,Trofeos
0,1,Agropecuario,Sojero,Carlos Casares - Buenos Aires,23-08-2011,Primera B Nacional,Ofelia Rosenzuaig,8000.0,Matias Fritzler,Diego Osella,0.0
1,2,Aldosivi,Tiburón,Mar del Plata - Buenos Aires,29-03-1913,Superliga,José María Minella,35354.0,Santiago Silva,Martín Palermo,0.0
2,3,All'Boys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Almagro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Alvarado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
60,61,Tigre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,62,Tristán Suarez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,63,Unión,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,64,Velez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,65,Villa Dálmine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN